version: 1
update_configs:
  - package_manager: "python"
    directory: "/requirements/prod"
    update_schedule: "live"
  - package_manager: "python"
    directory: "/requirements/dev"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
